# Screen settings
WIDTH = 800
HEIGHT = 600
SIZE = WIDTH, HEIGHT
BACKGROUND_COLOR = 255, 255, 255

# Bird settings
WEIGHT = 10
GRAVITY = WEIGHT * 0.00005
BIRD_WIDTH = 50
BIRD_HEIGHT = 50
BIRD_SIZE = BIRD_WIDTH, BIRD_HEIGHT
BIRD_PADDING_LEFT = 50
LIFT = 50

# Ground settings
GROUND_HEIGHT = 100
GROUND_SIZE = WIDTH, GROUND_HEIGHT
GROUND_POS = 0, HEIGHT - GROUND_HEIGHT

# Pipe settings
PIPE_VELOCITY = 0.1
PIPE_WIDTH = 70
PIPE_HEIGHT = 700
PIPE_SIZE = PIPE_WIDTH, PIPE_HEIGHT
PIPE_BASE_RANGE = 30
PIPE_DISTANCE_RANGE = 150
BETWEEN = 150
